### ISSUE TITLE
1 core at 100% after update to 0.2.0

### ISSUE THREAD

**Issue by Strit** [CGBassPlayer/seedtuber#5]
As the title says, after I updated to 0.2.0 this docker container uses 1 core at 100% all the time.

It didn't before.

I have turned the container off for now. :smile:

**Comment by CGBassPlayer** [comment]
Good catch! I didn't notice any crazy high usage when I tested it before release, but I will see what I can find

**Comment by eroc1990** [comment]
FWIW I'm running this on two different 1CPU 1GB RAM nanodes, and when it's live it pins my single core, rendering the rest of the services running on that box unreachabe. Running stock config, all defaults.

**Comment by CGBassPlayer** [comment]
Alright so I looked into this and it looks like the scheduler library I implemented in 0.2.0 is what is causing the pinning of a CPU core. 

I am going to revert back to way I was doing it in 0.1.0 and get a new version out for you guys

**Comment by CGBassPlayer** [comment]
Just published 0.2.1 to hopefully fix this issue

**Comment by Strit** [comment]
Awesome. Will try it when I get home. :)
